package io.github.fornewid.gradle.plugins.manifestshield.internal.sources

import io.github.fornewid.gradle.plugins.manifestshield.ManifestShieldConfiguration
import io.github.fornewid.gradle.plugins.manifestshield.ManifestShieldPlugin
import io.github.fornewid.gradle.plugins.manifestshield.internal.BlameLogParser
import io.github.fornewid.gradle.plugins.manifestshield.internal.EnabledCategories
import io.github.fornewid.gradle.plugins.manifestshield.internal.ShieldFlags
import io.github.fornewid.gradle.plugins.manifestshield.internal.ManifestExtraction
import io.github.fornewid.gradle.plugins.manifestshield.internal.ManifestVisitor
import io.github.fornewid.gradle.plugins.manifestshield.internal.applyConfig
import io.github.fornewid.gradle.plugins.manifestshield.internal.utils.ManifestListDiff
import io.github.fornewid.gradle.plugins.manifestshield.internal.utils.ManifestListDiffResult
import io.github.fornewid.gradle.plugins.manifestshield.internal.utils.ManifestListDiffResult.BaselineCreated
import io.github.fornewid.gradle.plugins.manifestshield.internal.utils.ManifestListDiffResult.DiffPerformed.HasDiff
import io.github.fornewid.gradle.plugins.manifestshield.internal.utils.ManifestListDiffResult.DiffPerformed.NoDiff
import io.github.fornewid.gradle.plugins.manifestshield.internal.utils.Messaging
import io.github.fornewid.gradle.plugins.manifestshield.internal.utils.OutputFileUtils
import io.github.fornewid.gradle.plugins.manifestshield.internal.utils.Tasks.declareCompatibilities
import io.github.fornewid.gradle.plugins.manifestshield.internal.utils.SourcesContentBuilder
import io.github.fornewid.gradle.plugins.manifestshield.models.ManifestComponent
import io.github.fornewid.gradle.plugins.manifestshield.models.ManifestEntry
import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

internal abstract class ManifestSourcesDiffTask : DefaultTask(), ShieldFlags {

    init {
        group = ManifestShieldPlugin.MANIFEST_SHIELD_TASK_GROUP
    }

    @get:InputFile
    abstract val mergedManifestFile: RegularFileProperty

    @get:InputFile
    abstract val blameLogFile: RegularFileProperty

    @get:Input
    abstract val configurationName: Property<String>

    @get:Input
    abstract val projectPath: Property<String>

    @get:Input
    abstract val rootProjectDir: Property<String>

    @get:Input
    abstract val shouldBaseline: Property<Boolean>

    @get:Input
    abstract val pluginVersion: Property<String>

    abstract override val guardUsesSdk: Property<Boolean>
    abstract override val guardUsesPermission: Property<Boolean>
    abstract override val guardUsesPermissionSdk23: Property<Boolean>
    abstract override val guardPermission: Property<Boolean>
    abstract override val guardActivity: Property<Boolean>
    abstract override val guardActivityAlias: Property<Boolean>
    abstract override val guardService: Property<Boolean>
    abstract override val guardReceiver: Property<Boolean>
    abstract override val guardProvider: Property<Boolean>
    abstract override val guardUsesFeature: Property<Boolean>
    abstract override val guardIntentFilter: Property<Boolean>
    abstract override val guardStartup: Property<Boolean>
    abstract override val guardSupportsScreens: Property<Boolean>
    abstract override val guardCompatibleScreens: Property<Boolean>
    abstract override val guardUsesConfiguration: Property<Boolean>
    abstract override val guardSupportsGlTexture: Property<Boolean>
    abstract override val guardQueries: Property<Boolean>
    abstract override val guardMetaData: Property<Boolean>
    abstract override val guardUsesLibrary: Property<Boolean>
    abstract override val guardUsesNativeLibrary: Property<Boolean>
    abstract override val guardProfileable: Property<Boolean>
    abstract override val exportedOnly: Property<Boolean>
    abstract override val requiredOnly: Property<Boolean>

    @get:OutputDirectory
    abstract val baselineDir: DirectoryProperty

    @get:Input
    abstract val filePrefix: Property<String>

    @TaskAction
    internal fun execute() {
        val manifest = ManifestVisitor.parse(mergedManifestFile.get().asFile)
        val configName = configurationName.get()
        val path = projectPath.get()
        val baseline = shouldBaseline.get()
        val dir = baselineDir.get()
        val prefix = filePrefix.get()
        val blameFile = blameLogFile.get().asFile
        if (!blameFile.exists()) {
            throw GradleException(
                "Manifest merger blame log not found at: ${blameFile.absolutePath}\n" +
                "This file is generated by AGP's manifest merge process.\n" +
                @Suppress("DEPRECATION")
                "Try running: ./gradlew ${path}:process${configName.capitalize()}MainManifest"
            )
        }
        val rootDir = rootProjectDir.orNull?.let { File(it) }
        val sourceMap = BlameLogParser.buildSourceMap(BlameLogParser.parse(blameFile, rootDir))

        val sourcesContent = SourcesContentBuilder.buildMergedWithSdk(
            manifest = manifest,
            sourceMap = sourceMap,
            projectPath = path,
            flags = EnabledCategories.from(this),
        )
        val baselineFile = OutputFileUtils.baselineFile(dir, "$prefix.sources")
        val category = "$prefix.sources"

        val result = if (baseline || !baselineFile.exists()) {
            baselineFile.writeText(sourcesContent)
            BaselineCreated(projectPath = path, configurationName = configName, category = category, baselineFile = baselineFile)
        } else {
            ManifestListDiff.performDiff(
                projectPath = path,
                configurationName = configName,
                category = category,
                expectedContent = baselineFile.readText(),
                actualContent = sourcesContent,
            )
        }

        when (result) {
            is HasDiff -> {
                val rebaselineMsg = Messaging.rebaselineMessage(path, configName)
                logger.error(result.createDiffMessage(withColor = true, rebaselineMessage = rebaselineMsg))
                throw GradleException(result.createDiffMessage(withColor = false, rebaselineMessage = rebaselineMsg))
            }
            is NoDiff -> logger.debug(result.noDiffMessage)
            is BaselineCreated -> logger.lifecycle(result.baselineCreatedMessage(withColor = true))
        }
    }

    internal fun setParams(
        config: ManifestShieldConfiguration,
        mergedManifest: org.gradle.api.provider.Provider<org.gradle.api.file.RegularFile>,
        blameLog: org.gradle.api.provider.Provider<org.gradle.api.file.RegularFile>,
        projectPath: String,
        rootProjectDir: File,
        baselineDirectory: org.gradle.api.file.Directory,
        filePrefix: String,
        shouldBaseline: Boolean,
    ) {
        this.mergedManifestFile.set(mergedManifest)
        this.blameLogFile.set(blameLog)
        this.configurationName.set(config.configurationName)
        this.projectPath.set(projectPath)
        this.rootProjectDir.set(rootProjectDir.absolutePath)
        this.shouldBaseline.set(shouldBaseline)
        this.pluginVersion.set(ManifestShieldPlugin.VERSION)
        applyConfig(config)
        this.baselineDir.set(baselineDirectory)
        this.filePrefix.set(filePrefix)
        declareCompatibilities()
    }
}
